import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NavigationBar from "/components/header/navigation";

const inter = Inter({ subsets: ["latin"] });
export const getStaticProps =  async (context) => {
  const productData = await( await fetch(`https://fakestoreapi.com/products`)).json()
  return {
      props: {
          productData,
      }
  }
}
export default function Home({productData}) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavigationBar/>
      </main>
      <footer>
      </footer>
    </>
  );
}
